Data Science

Data Structure:
1. Primitive
- Integer
- Float
- String
- Boolean
2. Non-primitive
- Dictionary
- Array
- Tuple
- Set
- File
- List: Linear (Stacks, Queues), Non-linear (Graphs, Trees)

Numpy Arrays
Differences btw np arrays and python lists:
- np arrays have a fixed size, if you change it, a new array is created and the old one is deleted
- np arrays require the same datatype
- np arrays perform calculations more effectively
- np arrays allow array-wise operations (vectorization) that can be used to get rid of inefficiencies of loops
- scikit learn is fed with np arrays

# Lists and Arrays

In [4]:
import numpy as np
#Creating tuples
tuple1=(1,2,3)
type(tuple1)
arr1=np.array(tuple1)
# arr1,
dict1={'one':1,'two':2,'three':3}
arr2=np.array(dict1)
arr2

array({'one': 1, 'two': 2, 'three': 3}, dtype=object)

Use lists to create arrays unless otherwise is needed

In [3]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
[i for i in np.arange(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
a2=np.array(np.arange(15))
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
len(arr1), arr1.size #both are the same thing. len is a function, size is an attribute

(3, 3)

lists vs np.arrays

In [6]:
a=[1,2,3]
b=[4,5,6]
a+b, 3*a

([1, 2, 3, 4, 5, 6], [1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
a+b,3*a,np.repeat(a,3),np.tile(a,3)
c=np.concatenate((a,b),axis=0)
c.mean(axis=1)
# to make it repeat itself
# in general, lists do not consider elements but np.arrays perform element-wise calculations


array([2., 5.])

In [28]:
a.argmin(),a.argmax()

(0, 2)

In [31]:
#Create an empty array without initializing any values.
empty_arr=np.empty((2,7))
empty_arr

array([[-2.31584178e+077, -2.31584178e+077,  3.95252517e-323,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]])

# Object Oriented Programming (OOP)

"__ init __" is the constructor

Example Code:

In [12]:
class Dog():

    
    def __init__(self, mybreed):
        #We take in arguments
        #We assign them to ATTRIBUTES
        self.breed=mybreed

In [14]:
new_breed=Dog(mybreed="Huskie")

In [16]:
new_breed.breed

'Huskie'

The attributes we create with "self" keyword belong to a single instance.

We need to create CLASS OBJECT ATTRIBUTE that are the same for every instance of a class.

In [ ]:
class Dog():

    species="mammal" #This is a class object attribute
    
    def __init__(self, mybreed):
        #We take in arguments
        #We assign them to ATTRIBUTES
        self.breed=mybreed

Methods are the functions defined inside of a class

In [34]:
class Dog():

    species="mammal" #This is a class object attribute
    
    def __init__(self, mybreed,myname):
        #We take in arguments
        #We assign them to ATTRIBUTES
        self.breed=mybreed
        self.name=myname
    def bark(self,number):
        print(f"Woof! My name is {self.name}! My specie is {self.species}. I am {number} years old.")

In [35]:
my_dog=Dog("Pomerian","Mac")
my_dog.bark(4)

Woof! My name is Mac! My specie is mammal. I am 4 years old.


Class Inheritence

In [53]:
class Dog2(Dog):

    def __init__(self,mybreed,myname):
        Dog.__init__(self,mybreed,myname) #Dog class is inherited
        print("Dog2 created")

In [54]:
# dog2=Dog2(mybreed="Pom",myname="BC")
dog2=Dog2("Pom" ,"BC")

Dog2 created


Generators

In [57]:
def create_cubes(n):
    for x in range(n):
        yield x**3

list(create_cubes(3))


[0, 1, 8]

In [58]:
round(3.1415,2)

3.14

# Advanced String Ops

In [61]:
a="Hello Jupyter"
a.count("J"),a.count("j"),a.find("J")

(1, 0, 6)

In [64]:
a.center(19,"z")

'zzzHello Jupyterzzz'

In [67]:
print("hello\thi")

hello	hi


In [68]:
a.isalnum() #Checks if all chars are alpha numeric


False

In [69]:
a.isalpha()

False

In [70]:
a.islower()

False

In [71]:
a.isupper()

False

In [75]:
b=" "
b.isspace()

True

In [76]:
a.endswith('r')

True

In [77]:
s="hihihihihi"
s.split("i"),s.partition("i")

(['h', 'h', 'h', 'h', 'h', ''], ('h', 'i', 'hihihihi'))

Sets

In [78]:
s=set()
s.add(1)
s.add(2)

In [80]:
s.add(2)
s

{1, 2}

In [81]:
s.clear()
s

set()

In [82]:
sc=s.copy()
s.add(4)
s.difference(sc)

{4}

In [84]:
s1={1,2,3}
s2={1,4,5}
s1.difference_update(s2)
s1

{2, 3}

In [85]:
s1.discard(2)
s1

{3}

In [88]:
s1.discard(12) #discard removes the item if it is included in the set, if not nothin happens
s1

{3}

In [90]:
s3={1,2,3}
s4={1,3,5}
s3.intersection(s4),s3

({1, 3}, {1, 2, 3})

In [92]:
s3.intersection_update(s4)

In [93]:
s3

{1, 3}

In [97]:
from hashlib import sha256


s5={1,2}
s6={1,2,4}
s7={5}

s5.isdisjoint(s6),s5.isdisjoint(s7)

(False, True)

In [99]:
s5.issubset(s6),s6.issuperset(s5)

(True, True)

In [100]:
s5.symmetric_difference(s6)

{4}

In [104]:
s6.difference(s5),s5.difference(s6),

({4}, set())

In [105]:
s5.union(s6)

{1, 2, 4}

In [106]:
s5.update(s6)
s5

{1, 2, 4}

# Dictionaries

In [107]:
d={'k1':1,'k2':2}
d

{'k1': 1, 'k2': 2}

In [108]:
{x:x**2 for x in range(10)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [112]:
{k:v**2 for k,v in zip(['a','b','c'],range(3))} #called as comprehensions

{'a': 0, 'b': 1, 'c': 4}

In [115]:
for k in d.items():
    print(k)
for k in d.keys():
    print(k)
for k in d.values():
    print(k)

('k1', 1)
('k2', 2)
k1
k2
1
2


# Lists

append vs extend

In [117]:
x=[1,2,3]
x.append([4,5])
x

[1, 2, 3, [4, 5]]

In [118]:
x=[1,2,3]
x.extend([4,5])
x

[1, 2, 3, 4, 5]

In [119]:
x.insert(2,10) #x.insert(where you want it, the object you want)

In [120]:
x

[1, 2, 10, 3, 4, 5]

In [124]:
x.reverse() #already inplace
x

[10, 5, 4, 3, 2, 1]

In [123]:
x.sort() #already inplace
x
x

[1, 2, 3, 4, 5, 10]