In [17]:
import pandas as pd
import numpy as np
import torch

In [1]:
A=[[-1,4],[2,-2]]

In [5]:
lambdas, V = np.linalg.eig(A)

In [6]:
lambdas #EIGENVALUES

array([ 1.37228132, -4.37228132])

In [8]:
v= V[:,0]
v

array([0.86011126, 0.51010647])

In [9]:
lambda_0=lambdas[0]

In [10]:
Av=np.dot(A,v)

In [13]:
Av,lambda_0*v  #BOTH ARE THE SAME SINCE Av=lambda*v

(array([1.18031462, 0.70000958]), array([1.18031462, 0.70000958]))

In [23]:
np.linalg.det(A)

-6.0

In [25]:
lambdas[0]*lambdas[1] #DETERMINANT IS EQUAL TO THE MULTIPLICATION OF ALL EIGENVECTORS

-6.0

Now, in PyTorch

In [21]:
A_p=torch.tensor([[-1,4],[2,-2.]])
A_p

tensor([[-1.,  4.],
        [ 2., -2.]])

In [22]:
eigens = torch.eig(A_p, eigenvectors=True)
eigens

/var/folders/t6/nkv95bj97gv9j73w9bfk2p0r0000gn/T/ipykernel_7464/1104588676.py:1: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:3427.)
  eigens = torch.eig(A_p, eigenvectors=True)


torch.return_types.eig(
eigenvalues=tensor([[ 1.3723,  0.0000],
        [-4.3723,  0.0000]]),
eigenvectors=tensor([[ 0.8601, -0.7645],
        [ 0.5101,  0.6446]]))

In [24]:
torch.det(A_p)

tensor(-6.)

Eigendecomposition

In [28]:
A = np.array([[4,2],[-5,-3]])
lambdas,V = np.linalg.eig(A)
Vinv = np.linalg.inv(V)
Lambda=np.diag(lambdas)


(array([ 2., -1.]),
 array([[ 2.,  0.],
        [ 0., -1.]]))

In [30]:
np.dot(V,np.dot(Lambda,Vinv)),A  #THIS WAS THE ORIGINAL THEORY

(array([[ 4.,  2.],
        [-5., -3.]]),
 array([[ 4,  2],
        [-5, -3]]))